M4bulmagd remove hls
voicelab-org/labelit pull request #99
Opened 2023-04-01 19:49 UTC by m4bulmagd

2023-04-01 21:45 UTC, m4bulmagd commented
this test passed locally but failed here because it checked for files in a storage bucket. any idea how it work here ?

2023-04-04 08:15 UTC, corentingiraud requested changes
Very good work ! As a lot of this has been removed, we might deploy in staging first to check if the project work as expected :)

2023-04-04 08:15 UTC, corentingiraud commented on backend/src/labelit/utils/audio_utils.py
> +            os.getenv("MIN_AUDIO_SIZE_TO_GENERATE_PEAKS", 4)
settings.py might be a better place for this ?

2023-04-04 08:15 UTC, corentingiraud commented on docker-compose.yaml
> +    #image: minio/minio:RELEASE.2023-01-02T09-40-09Z #had some issue with this ver
Keep the newer version in the repository, even if in your local system you use a different one.

2023-04-04 09:09 UTC, corentingiraud commented on docker-compose.yaml
> +    #image: minio/minio:RELEASE.2023-01-02T09-40-09Z #had some issue with this ver
By the way, what problem do you have with the new version ?
You might need to delete the docker volume.

2023-04-04 12:54 UTC, corentingiraud approved these changes
LGTM 👍

2023-04-04 12:54 UTC, merged